### ISSUE TITLE
Braille: Binomial notation for Nemeth and UEB

### ISSUE THREAD

**Issue by mcantino1** [NSoiffer/MathCAT#100]
Hi! I used your MathCAT Demo page to test out the braille translation of different expressions, and I found an issue with the binomial notation in both Nemeth and UEB. 
In your UEB transcription, the elements of the binomial are separated and presented in their own individual parentheses. There is no indicator present to show that one is beneath the other. See 14.3.3 Vertical Juxtaposition in the [UEB Technical Guidelines](https://iceb.org/guidelines_for_technical_material_2014.pdf).
In your Nemeth translation, the parentheses have been replaced by enlarged brackets. There is an 8-dot character where the Nemeth "directly under" indicator should be. There is also a space inserted after the first variable which should not be present. The Nemeth UEB manual was recently updated, but you can find the reference under "12.7.1 Binomial Coefficient" in this copy of the [Nemeth within UEB manual](https://drive.google.com/file/d/1YeLgaijLsna6izh5bOsgQeOmAJpdyVJi/view) (this version is from May 2020).

**Comment by NSoiffer** [comment]
Thanks for looking for bugs. What was the input you used for the binomial? If I use `$\binom{n}{q}$`, I get
* Nemeth: ⠷⠝⠩⠟⠾
* UEB: ⠐⠣⠝⠰⠻⠟⠐⠜

These match the referenced manuals.

The equivalent MathML is:
```
<math>
  <mrow>
    <mo>(</mo>
    <mfrac linethickness='0'>
      <mi>n</mi>
      <mi>q</mi>
    </mfrac>
    <mo>)</mo>
  </mrow>
 </math>
```
This MathML generates the same braille as the LaTeX input.

Binomial notation is a bit tricky because the alternative that is sometimes used is a 2x1 matrix. The latex for this is `$\begin{pmatrix} n \\ k \end{pmatrix}$` and the corresponding MathML is:
```
<math>
  <mrow>
    <mo>(</mo>
    <mtable>
      <mtr>
        <mtd>
          <mi>n</mi>
        </mtd>
      </mtr>
      <mtr>
        <mtd>
          <mi>k</mi>
        </mtd>
      </mtr>
    </mtable>
    <mo>)</mo>
  </mrow>
 </math>
```

Based on what you wrote, I think you used this `mtable` input. Is that correct? If so, unfortunately there is no way to tell the difference between a 2x1 column matrix/vector and the binomial coefficient. 

The W3C Math Working Group has some ideas of how to mark this up as a binomial. MathCAT is a testbed for these ideas and I tried what I thought would work and realized that I only made this work for speech and not braille. The binomial form is only one of three notations I've identified where Braille requires knowledge of the semantics of the notation. The other two are `:`  (ratio vs not-ratio) and `|` (spaces around it when used as a sign of comparison vs. absolute value, etc).  If you know of more cases where the interpretation of some notation makes a difference, please let me know as I need to deal with that somehow in the braille generation.

I'll add an issue to make sure the braille checks for this form. FYI, the tentative plan for MathML 4 for a binomial using a 2x1 table would be written as:
```
<math>
  <mrow intent='binomial($arg1, $arg2)'>
    <mo>(</mo>
    <mtable>
      <mtr>
        <mtd>
          <mi arg='arg1'>n</mi>
        </mtd>
      </mtr>
      <mtr>
        <mtd>
          <mi arg='arg2'>k</mi>
        </mtd>
      </mtr>
    </mtable>
    <mo>)</mo>
  </mrow>
 </math>
```

**Comment by mcantino1** [comment]
Hi Neil,
That was a speedy response! Thanks for the explanation. That makes a lot of
sense. I don't have MathType and I don't know LaTeX, so I was using Equatio
to produce MathML. I know that Equatio's MathML can be less than ideal, but
it worked well for all the other expressions that I entered into the
MathCAT demo. Given your explanation, it makes sense that Equatio would try
to produce this notation as a 2x1 matrix, resulting in translation issues.

Here's the MathML output from Equatio.

<math xmlns="http://www.w3.org/1998/Math/MathML" display="block">
  <mrow data-mjx-texclass="INNER">
    <mo data-mjx-texclass="OPEN">(</mo>
    <mtable columnalign="left" columnspacing="1em" rowspacing="4pt">
      <mtr>
        <mtd>
          <mi>n</mi>
          <mo>&#x2212;</mo>
          <mn>1</mn>
        </mtd>
      </mtr>
      <mtr>
        <mtd>
          <mi>k</mi>
          <mo>&#x2212;</mo>
          <mn>1</mn>
        </mtd>
      </mtr>
    </mtable>
    <mo data-mjx-texclass="CLOSE">)</mo>
  </mrow>
</math>

I don't know enough about MathML to interpret the code effectively, but I
do see the mtable and mtr that you mentioned.

I think I can likely come up with some other Nemeth rules that are context
dependent. I'll keep this in mind, and I'll follow up with you if I come up
with anything. I actually tried several expressions with colons while
working with the MathCAT demo yesterday. MathCAT seemed to nail everything.
Whenever I was expecting a colon, MathCAT transcribed a colon. Whenever I
was expecting a ratio symbol, MathCAT transcribed a ratio symbol. I don't
think this is an issue in UEB since the same symbol is used for a colon and
a ratio.
Off the top of my head, I know that spacing for some signs of omission (the
general omission symbol and shapes used for omission) are context dependent
in Nemeth. Signs of omission are meant to be "spaced in accordance with the
rules for the omitted material it represents." In general, operators are
unspaced from the surrounding content and comparison symbols have spaces on
either side.

Speaking of general omission, it seems like this might be missing from
MathCAT. This comes up a lot in lower grades. I don't know how relevant
this is for your work.

Here's more Equatio MathML for the expression 92 ÷ 2 = ?
<math xmlns="http://www.w3.org/1998/Math/MathML" display="block">
  <mn>92</mn>
  <mo>&#xF7;</mo>
  <mn>2</mn>
  <mo>=</mo>
  <mo>?</mo>
</math>
Here's the MathCAT braille output.
⠼⠔⠆⠨⠌⠆⠀⠨⠅⠸⠦
The final two characters should be a space and a full cell (ASCII is =)

For the expression 6 + ? = 15
<math xmlns="http://www.w3.org/1998/Math/MathML" display="block">
  <mn>6</mn>
  <mo>+</mo>
  <mo>?</mo>
  <mo>=</mo>
  <mn>15</mn>
</math>
⠼⠖⠬⠸⠦⠀⠨⠅⠀⠼⠂⠢
Here the spacing is correct, but the ASCII characters _8 should be =

I'll reach out to you if I come up with anything else.
Thanks for following up on this! I'll respond to your other email as soon
as I can.

Michael Cantino

**Comment by NSoiffer** [comment]
Fixed omission issue in https://github.com/NSoiffer/MathCAT/commit/5da06dd940ca7708374e6fb0bdb68bc23166944b, so all the problems are now resolved.

**Comment by mcantino1** [comment]
Hi Neil,
It's exciting to see all these updates come through! Thanks for patching
things up so quickly. I'll let you know if I spot any more bugs or if I
come up with any good challenge cases. Have a good day!

Michael Cantino
