### ISSUE TITLE
Braille for Nemeth in first column of a table is wrong

### ISSUE THREAD

**Issue by NSoiffer** [NSoiffer/MathCAT#102]
When the first column of a table starts with a number, it needs to have the number indicator. See green book 9c, page 11. This currently doesn't happen because the more general rule is that it is not needed after a `(`.

**Comment by mcantino1** [comment]
Just to clarify, this rule only applies to matrices. If it was a standard braille table, then the typical Nemeth rules would apply. 

For example, if an entry in the first column of a standard braille table was (1), then a numeric indicator would not be used for that number because it is touching the grouping symbol.
