### ISSUE TITLE
Missing row indicators for matrices in SimpleSpeak?

### ISSUE THREAD

**Issue by brichwin** [NSoiffer/MathCAT#112]
Is the absence of row number announcement deliberate in SimpleSpeak? When MathCAT is configured with output for blindness,
for:
![image](https://github.com/NSoiffer/MathCAT/assets/117550/df44be91-7e01-4b61-9bc4-815c9b064779)
```tex
\begin{pmatrix}
1 & 0 & 0\\
0 & 1 & 0\\
0 & 0 & 1
\end{pmatrix}
```

ClearSpeak Verbose, Medium, and Terse produce:
```text
the 3 by 3 matrix; row 1; 1, 0, 0; row 2; 0, 1, 0; row 3; 0, 0, 1;
```

However, SimpleSpeak Verbose, Medium, and Terse produce:
```text
the 3 by 3 matrix; column 1; 1; column 2; 0; column 3; 0; column 1; 0; column 2; 1; column 3; 0; column 1; 0; column 2; 0; column 3; 1;
```
Note that the row number is not indicated.

**Comment by NSoiffer** [comment]
ClearSpeak has special rules for "simple" matrices that are 3x3 or smaller so that they are spoken more quickly with less clutter. I probably should use them for SimpleSpeak because "less clutter"/faster is a goal of SimpleSpeak.

The "SpeakColNum" preference should force them to be spoken. I have tests for that option, so hopefully that works...
