### ISSUE TITLE
Proper pronounciation of multicharacter symbols

### ISSUE THREAD

**Issue by RichCaloggero** [NSoiffer/MathCAT#132]
- https://direct.mit.edu/artl/article/29/2/198/115422/Interdependent-Self-Organizing-Mechanisms-for?searchresult=1

At the above article, there are many math expressions whose symbols are multicharacter. NVDA speels these out character-by-character, and when you drill down into the expression via mathcat, each character becomes a node in the tree.

WOuld it be possible to treat these as single atomic units?

I don't know MathML well, so not sure if multicharacter symbols are possible in MathML.

**Comment by NSoiffer** [comment]
I'm not sure what exactly you are asking to change. Can you point to an example piece of math?

I tried something that I thought you might be asking about -- some math at the end of 2.3.3. The display equation reads as:
```
u     sub      i     raised to the      c      r   d     power    is is equal to 2 cases
case 1   0      if    r     is greater than or equal to     t       h 
case 2     negative  u    of   open paren   p   sub   i   comma    m   comma    r     close paren  otherwise    
```
[ignore the random spacing -- I copied this from NVDA's speech viewer]

You can see "crd" and "TH" are spelled out. However, that's not surprising since they are single character tokens in the MathML.
I suspect that is a mistake in the MathML generator or by the author. The equation at the end of 4.2.2 is definitely wrong in this respect. "ReceivedOffer", "agent", etc., have each letter as an individual `mi`. "ReceivedOffer" should be a single `mi`, etc. Besides being more mathematically correct to be a single identifier, it will also look better visually because it won't be in italics. The screen reader would read it as "ReceivedOffer" rather than spelling it out, which is very likely what is desired. 

I strongly suggest looking at your tool chain. It is producing lots of "HTML math" (use of `<em>`, `<sub>`, and `<sup>`) for the math. This turns into an accessibility disaster. Besides not getting the braille right (there's a separate math code for braille), the speech is wrong if (as is often the case, the screen reader's speech settings have "punctuation" set to some lower level than "most" or "all" -- people don't like to hear all the commas and periods in sentences. With those settings, the inline math example at the end of 2.3.3 speaks as:
```
where the utility mapping U p i M R is specified in link  section 4.1 
```
Notice that the parens, commas, and subscript don't get spoken.

If the author meant some content to be math, it should be in MathML. Otherwise, it will likely not be accessible.

**Comment by RichCaloggero** [comment]
>4.2.2 is definitely wrong in this respect. "ReceivedOffer", "agent", etc., have each letter as an individual mi. "ReceivedOffer" should be a single mi, etc. Besides being more mathematically correct to be a single identifier, it will also look better visually because it won't be in italics. The screen reader would read it as "ReceivedOffer" rather than spelling it out, which is very likely what is desired.

Thank you; that was my thought as well.

>I strongly suggest looking at your tool chain. It is producing lots of "HTML math" (use of <em>, <sub>, and <sup>) for the math. This turns into an accessibility disaster.

I know there are probably lots of correct answers to this question, but do you have a suggestion for a toolchain? This example came from an open access journal article, and I'd like to comment on it, but I have no direct experience producing mathML, and of course, have no idea what the original article submission might have looked like.

Thank you for all you do!

-- Rich Caloggero, MIT Disability and Access Services

**Comment by NSoiffer** [comment]
If it starts in TeX, `tex4ht`, `pandoc`, and `latexml` are good. I think `pandoc` uses `MathJaX`, but I could be misremembering.

If you start with a Word doc, it matters whether the math was created with MathType or Word's editor. Again, `pandoc` is one solution. Creating an ebook using the (free) DAISY Word->EPUB converter) and then pulling out the HTML file from the ebook is another option.
