### ISSUE TITLE
Expressions which begin with a root which has an index are translated incorrectly

### ISSUE THREAD

**Issue by rob-aph** [NSoiffer/MathCAT#137]
Consider the following:
```
<math>
    <mroot>
        <mn>27</mn>
        <mn>3</mn>
    </mroot>
</math>
```
MathCAT gives the result:
⠰⠩⠔⠼⠉⠼⠃⠛⠬

Result should be:
⠰⠰⠩⠔⠼⠉⠼⠃⠛⠬

Grade 1 word mode is required in this instance to prevent the second symbol from being interpreted as the "in" contraction.

I tried fixing this myself, and determined that perhaps the problem is in the function is_grade2_string_ok in braille.rs, but I don't know Rust, and couldn't get any further.

**Comment by NSoiffer** [comment]
Thankfully, the fix was simpler: The G1 indicator was missing in the `mroot` rule in front of the `⠔`:
```
   name: default
   tag: mroot
   match: "."
   replace: 
   - t: "1⠩1⠔"
   - test:
  ...
```

I have a test that should have caught this, but maybe I made a copy/paste typo and one of the initial G1 indicators was left out so the test passed.

Thanks for the bug report -- this may be the first UEB bug report I've heard about. That's probably more of a reflection of how many UEB users there are rather than the quality of the code. This isn't an obscure bug...
