### ISSUE TITLE
Trouble getting spaces / minor formatting through

### ISSUE THREAD

**Issue by rob-aph** [NSoiffer/MathCAT#144]
[_Updated to put MathML in block quotes so it displays properly_]
We are finding it difficult to get minor formatting through MathCAT. For example, we might want spaces around operators, or just want to display a row of numbers on a line without rolling them into one number.

I have had limited success using non-break space:
```
<math>
    <mn>5</mn>
    <mtext>&nbsp;</mtext>
    <mo>+</mo>
    <mtext>&nbsp;</mtext>
    <mn>5</mn>
</math>
```
This renders the intended result, but I have found stuffing non-break spaces between everything I want spaced has occasional side effects. Consider the following side effect:
```
<math>
    <mn>123</mn>
    <mtext>&nbsp;</mtext>
    <mn>456</mn>
</math>
```

This produces:
⠼⠁⠃⠉⠐⠙⠑⠋
(Has an unexpected dot 5 between the two triplets of digits.)

The following, however, works as expected:
```
<math>
    <mn>12</mn>
    <mtext>&nbsp;</mtext>
    <mn>34</mn>
</math>
```
Result:
⠼⠁⠃⠀⠼⠉⠙

Is there a proper way to do this that I am missing? Is it even reasonable to expect something like this from MathCAT?

**Comment by NSoiffer** [comment]
MathCAT tries to repair common mistakes people/software makes in generating MathML. Numbers are an area where mistakes are common because spaces, commas, and periods tend to split the number apart into separate `mn`s. MathCAT's heuristic is to look for blocks of three digits and put them back together into a single `mn` if there are spaces, commas, or periods separating them. This improves the speech and the braille. Based on your example, you have UEB output and the dot-5 is due to rule 6.6 in the [ICEB Rules](https://iceb.org/Rules%20of%20Unified%20English%20Braille%202013%20(linked).pdf).

The workaround (which I admit is ugly) is to add an invisible character next to the `&nbsp;`. This won't show up in the braille or speech in this case. For example, the following will do what you want because MathCAT won't think it is a single number:
```
<math>
    <mn>123</mn>
    <mtext>&nbsp;&#x2063;</mtext>
    <mn>456</mn>
</math>
```
`&#x2063;` is an invisible separator character.

In trying this example, I discovered that invisible chars are being sent to the speech engine when part of a multi-char string. This does not affect the speech (at least not with the speech engine I tried). However, I just pushed a fix so they aren't sent out.

Please close the issue if this solves your problem.

**Comment by rob-aph** [comment]
Solution is looking great so far. I'll go ahead and close and open another issue if something comes up.

I can't tell you how greatful I am for your solution for this issue, and with other of our concerns so far. Thank you!

**Comment by rob-aph** [comment]
I tried your suggested trick of using no-break space and invisible separator to get spaces through, but some undesirable side-effects appeared when using Nemeth. Consider the following:
```
<math>
    <mi>y</mi>
    <mtext>&#x00a0;&#x2063;</mtext>
    <mo>=</mo>
    <mtext>&#x00a0;&#x2063;</mtext>
    <mn>5</mn>
</math>
```

The result is:
⠰⠽⠀⠨⠅⠀⠼⠢

The result has an undesirable English letter sign before the y.

I have also had situations where the number sign was used where it shouldn't have been. Is there any way to avoid these issues?

**Comment by NSoiffer** [comment]
I added `&#x2063;` to `&#x00a0;` as something that is ignored in `mtext`. That solves the problem, at least for the case you mention. If it solves it for your other problem cases, please close (again).

**Comment by rob-aph** [comment]
Actually, the latest change breaks spaces between individual numbers:
```
<math>
    <mn>1</mn>
    <mtext>&#x00a0;&#x2063;</mtext>
    <mn>3</mn>
    <mtext>&#x00a0;&#x2063;</mtext>
    <mn>5</mn>
</math>
```

**Comment by NSoiffer** [comment]
I just gave it a try and get `⠼⠁⠀⠼⠉⠀⠼⠑` which seems correct.

**Comment by rob-aph** [comment]
Sorry, I should have specified that the problem occurs when using Nemeth, not UEB.

**Comment by rob-aph** [comment]
I'm getting:
⠼⠂⠒⠢

**Comment by NSoiffer** [comment]
I've fixed that so it gives `⠼⠂⠀⠼⠒⠀⠼⠢`.

I maybe wasn't clear about the `&#x2063;` hack: it is only needed between blocks of three digit numbers. It doesn't hurt to use it between other numbers. E.g.,  both
```
<math><mn>1</mn><mtext>&#x00a0;</mtext><mn>3</mn><mtext>&#x00a0;</mtext><mn>5</mn></math>

<math><mn>1</mn><mn>3</mn><mn>5</mn></math>
```
return the correct braille string after my fix.

However, using it in
```
<math>
    <mi>y</mi>
    <mtext>&#x00a0;&#x2063;</mtext>
    <mo>=</mo>
    <mtext>&#x00a0;&#x2063;</mtext>
    <mn>5</mn>
</math>
```
is problematic.  The reason is `y` now has whitespace after it, making it a "single letter" (rule 25). This means it should have the English Letter indicator. _MathCAT is back to generating the English Letter indicator_.

Long technical explanation of how MathCAT works... The cleanup code coalesces multiple spaces into a single space because spaces don't affect speech and AFAIK, should add only 0 or 1 spaces to the braille (depending on the code/context). Also, some editors allow a user to type a space and others don't without effort because that tends to be bad math typography. So spaces in math are likely mistakes that MathCAT leans toward dropping in many situations.

My reading of the Nemeth rules is that spaces around identifiers are almost always thrown out. So that's what MathCAT does, and that why
```
<math>
    <mi>y</mi>
    <mtext>&#x00a0;</mtext>
    <mo>=</mo>
    <mtext>&#x00a0;</mtext>
    <mn>5</mn>
</math>
```
doesn't generate an English Letter Indicator. Because `=` is a comparison operator, it gets spaces around it in the output. When the `;&#x2063;` hack is used, the rules don't pickup  on it being whitespace, so it isn't thrown out and whitespace is considered to be after the `y`, making it a "single letter". So I think that the English Letter Indicator is actually correct here.

I'm not an expert though (even though my code pretends to be one :-). If this interpretation is wrong, please let me know why.

**Comment by NSoiffer** [comment]
@rob-aph: if you had the input:
```
<math><mn>1</mn><mn>3</mn><mn>5</mn></math>
```
Would you expect `⠼⠂⠀⠼⠒⠀⠼⠢` or `⠼⠒⠢` as the output?

One the one hand, it's a sequence of numbers, which means a sequence of digits, so no spaces. On the other hand, it seems like it should be different from `<mn>135</mn>`.

Thoughts?

**Comment by rob-aph** [comment]
With regard to:
```
<math><mn>1</mn><mn>3</mn><mn>5</mn></math>
```

This is a tough one. My knee jerk reaction is that it should be ⠼⠂⠀⠼⠒⠀⠼⠢ but a justification is tricky. Thoughts like, "Why a space", and "If a space, how many", come to mind.

This is why we have decided to use the non-break space / invisible separator trick any time we have a space in our content. This gives some preservation of intended formatting.

In UEB, for example, it is apparently common for young children to be tought addition with spaces around the plus sign to make equations easier to read. So, we support spaces and no spaces around operators, for example.

**Comment by rob-aph** [comment]
On the y = 5 issue:

I guess I'm expecting no English letter indicator, because, in my mind, it should perform the same with or without the invisible separator. This is because any time I want a space, I send no-break space followed by the invisible separator, no exceptions.

Would it be better if I sent just the no-break space when using Nemeth, and sent no-break space and invisible separator in UEB mode? UEB mode is working perfectly at the moment using both together. Note: I haven't tested Nemeth with just no-break space.

**Comment by NSoiffer** [comment]
In the Nemeth green book, there is example 9e(5), which is a bold "43" followed by a regular "56". It is an example where two `mn`s are needed. No space is used, so I need to back out of the change I made that adds a space.

> In UEB, for example, it is apparently common for young children to be tought addition with spaces around the plus sign to make equations easier to read. So, we support spaces and no spaces around operators, for example.

I think a much better solution is to add an option to MathCAT that you can set that would add spaces around all operators. Would that solve your problem? If so, would the extra space apply to invisible operators such as between the `2` and the `x`  `2x`?

**Comment by rob-aph** [comment]
I'll try to enumerate our use of spaces:

- Including text content with math. (your hak works great for including leading and trailing spaces in mtext blocks.)
- Writing a list of numbers without operators. (For now, we preserve space between numbers because it seems like a reasonable thing to do, but some day we plan to tackal spacial math.)
- Because of the younger children learning UEB Math issue mentioned earlier, it seemed easier to just preserve spaces, regardless of where or how many. This way, you could enter "1 + 3" on one line, and "1+3" on the line below, and format would be preserved for contrasting.

Thus far, we have been sending all content through MathCAT, regardless of the ratio of math to text in a given paragraph. I'm beginning to wonder if this is the best approach.

**Comment by rob-aph** [comment]
I like your fix for Nemeth which puts spaces between numbers, but it does break the green book example 9e(5) you mentioned.

**Comment by NSoiffer** [comment]
I've backed out the adding spaces between numbers in Nemeth because it breaks examples in the spec.

#183 is for discussion of an option to add spaces around all operator in UEB.

**Comment by rob-aph** [comment]
There was a commit a while back where using no-break space followed by invisible separator between numbers didn't include spaces in the output when using Nemeth. This has been fixed. I am still using these characters between everything for spaces in our app, and that causes some issues as you warned, but we are planning a major refactoring soon, and I can live with things the way they are for now.

**Comment by NSoiffer** [comment]
If you feel this is resolved, please close it. Otherwise, I'm not clear what is left to do, so I'd appreciate a summary.
