### ISSUE TITLE
UEB Literary Translation

### ISSUE THREAD

**Issue by rob-aph** [NSoiffer/MathCAT#147]
Perhaps because I'm new around here, I am having trouble understanding what MathCAT translates and what it doesn't. I am getting mixed grade 2 translations for text in <mtext> blocks. I translated the following sentence in a mtext block into UEB:
I cannot arrive at a conclusion for the behavior observed.

I received the following result:
⠠⠊⠀⠉⠁⠝⠝⠕⠞⠀⠜⠗⠊⠧⠑⠀⠁⠞⠀⠁⠀⠉⠕⠝⠉⠇⠥⠎⠊⠕⠝⠀⠿⠀⠮⠀⠃⠑⠓⠁⠧⠊⠕⠗⠀⠕⠃⠎⠻⠧⠑⠙⠲

What puzzles me is that some of the output is grade 2, and some clearly isn't. The "ar" contraction in "arrive" is translated, while the "be" in "behavior" is not. The word "observed" has an "er" contraction, but not an "ed" contraction.

Is any of this expected?

**Comment by NSoiffer** [comment]
You left out the sentence.

In any case, this is definitely a weak point in MathCAT: it doesn't know all the rules about contractions in UEB. It knows enough so that math terms such as "sin" get proper contractions, but it will definitely fail when given arbitrary text. I suppose one option would be to set math that contains a longer string of mtext in G1 passage mode. It would be technically correct but not ideal. Or maybe gather up all the contractions used in UEB and if any of them are in the string (and not handled by MathCAT already), set G1 mode. That avoids having to figure out whether the contraction applies in the string.

Short of spending (probably) months trying to implement all the rules of G2 UEB, do you have any suggestions for what to do?

**Comment by rob-aph** [comment]
Sorry about the sentence. It was actually included, but since its subject matter pertains to this discussion, it was ambiguous. The sentence was:

I cannot arrive at a conclusion for the behavior observed.

Now, to the real question -- what to do. I mainly brought this up because we would ultimately like the user to be able to control whether grade 1 or grade 2 is presented in our app. I think you're right about not wanting to attempt to become a literary Braille translator, otherwise, you would be basically rewriting liblouis, and you would need to write rules for all supported languages.

Perhaps not attempting to use grade 2 for anything in <mtext> blocks is a reasonable start. (I don't know how possible this is in your design.) This would be good, because it would be clear that MathCAT isn't trying to be a literary grade 2 translator, and the caller could decide what to do with the output. This could be a setting of course.

The problem with this approach is that callers might want grade 2 output, but there is no way to tell after translation what is math and what is text. If we could tell from the output which chunks were originally in <mtext> blocks, we could run the result through liblouis if grade 2 translation were desired. Is something like this possible or even reasonable?

**Comment by NSoiffer** [comment]
Internally, the UEB generation decides on a starting mode. When I wrote that code, I meant to add an option to control whether MathCAT generates G1 or G2 for the math. I see I didn't. I'll add one called "UEB_START_MODE" with values "Grade1" and "Grade2". That is something you should add to your SetPreference() calls (when it is implemented).

I could also add an option that controls whether mtext is translated or not. Or it could translate it as G1 and mark the start and stop with a non-braille characters that would be easy to find/replace. Any preferences or alternative suggestions?

**Comment by rob-aph** [comment]
I really like the idea of an option to output mtext blocks untranslated, and markers for the start and stop of these blocks. It would be interesting to hear what others think.

Using strictly G1 for something like this is complicated, because if one wanted G2, they would need to reverse translate from G1 before translating to G2.

That said, an option to use strictly G1 in mtext blocks would probably be useful to some, since the entire output would be Braille, with no partial G2 in text.

**Comment by andrew-l-d** [comment]
Apologies if I am off the mark.  I currently do not have a Braille display and am a bit rusty on codes.  For content that is at all likely to be ambiguous with grade 2 Braille, I am a big fan of grade 1 or, better, computer grade.
Andrew

**Comment by NSoiffer** [comment]
@andrew-l-d: the only fully safe thing for MathCAT to do is to put the entire expression in Grade 1 passage mode when it sees `mtext` with letters (`mtext` often used with non-breaking spaces, so not all `mtext` should trigger it). That's probably overkill and I can likely detect, at least for English, most cases that _might_ cause a problem. I have no idea what rules are like for other languages. Of course, they wouldn't be UEB so I'd have to do something special for them anyway (I'm working on that now for Vietnam braille).

Personally, I think it is nutty that things like "sin x" are brailled with a contraction but "2sin x" is not. Math involves lots of pattern recognition and changing how things look because a character differs here or there makes solving math problems that much harder. I think all math should be set as G1. My opinion comes with a whale-sized "but" -- I don't read braille. I used to lots of math, and I know that if the notation switched around in a problem, doing the math would be much harder.

I'm definitely open to hearing other ideas for solutions.

**Comment by NSoiffer** [comment]
In 5c72f60 I added a preference `UEB_START_MODE` with valid values `Grade1` and `Grade2`.

If  `Grade1` is used, it the responsibility of the caller to add any Grade 1 mode indicators around the math if they are needed.

**Comment by andrew-l-d** [comment]
Neil, I totally agree with your comment about switching notation causing problems.  I cautiously suggest that all equations should be shown in grade 1 or at least having an option to do so.

Andrew

**Comment by NSoiffer** [comment]
No comments in a while. Closing.
