### ISSUE TITLE
UEB: Need support for arc over previous

### ISSUE THREAD

**Issue by rob-aph** [NSoiffer/MathCAT#150]
UEB Math uses the following dot pattern to indicate arc over previous:
⠨⠸⠱

I believe the input symbol that should map to this functionality is U+2322. This character is already supported in Nemeth mode.

**Comment by NSoiffer** [comment]
You're right that arc is U+2322. However, I don't know what a standalone 'arc' symbol is in UEB. Section 12 of the [ICEB technical manual](https://iceb.org/guidelines_for_technical_material_2014.pdf) only lists what it should be for over an item, not standalone. My guess would be `⠸⠱` (dropping the first char), but that is `~` over an item. If you find something that shows what it is otherwise, let me know.

**Comment by rob-aph** [comment]
As I wrote this issue, I knew something felt wrong. Now I know what it is; you need a dot pattern to map directly to U+2322. I'll look, but I'm not optimistic I'll find anything.

**Comment by NSoiffer** [comment]
Please close the issue if you don't find anything in the next few days.

**Comment by rob-aph** [comment]
I was unable to find a UEB character for arc.
