### ISSUE TITLE
UEB: Need support for question mark over equals

### ISSUE THREAD

**Issue by rob-aph** [NSoiffer/MathCAT#151]
UEB Math uses the following dot pattern for question mark over equals:
⠰⠰⠦⠻⠐⠶

This is kind of a tricky one, because the first two symbols, the question mark and the vertical juxtaposition indicator need to be in Grade 1 mode, thus my use of dots 5 6 twice here.

**Comment by NSoiffer** [comment]
That's U+225F (≟). Where did you get that definition from? Often these characters are built out of the rules for putting one symbol above another. 14.3.3 of the [ICEB technical guide](https://iceb.org/guidelines_for_technical_material_2014.pdf) says
> 14.3.3 Vertical Juxtaposition, ⠻
The upper symbol should be given first, followed by the vertical juxtaposition
indicator, then the lower symbol.

That gives something more like `⠰⠰⠐⠶⠻⠦`, which is the opposite order for the symbols you give. Which is correct?

AFAIK, the equals sign does _not_ require G1 mode, but the vertical justification symbol and the question mark do. Because the G1 indicators are not forced (i.e., use them when not in G1 mode but don't use them if in G1 mode), in MathCAT this would be written as `⠐⠶1⠻1⠦` and MathCAT figures out if they are needed and if G1 word or passage mode is better. I did a quick test with my version of the with MathCAT and it ends up choosing between starting in:
```
Symbol mode:  ⠰⠭⠀⠐⠶⠰⠻⠰⠦⠀⠰⠽
Word mode:    ⠰⠰⠭⠀⠐⠶⠰⠻⠦⠀⠰⠽
Passage mode: ⠰⠰⠰⠭⠀⠐⠶⠻⠦⠀⠽⠰⠄
```
MathCAT chooses the passage mode because it avoids the G1 context switch and is only one character longer.

Thoughts?

**Comment by rob-aph** [comment]
I got the definition from:
https://uebmath.aphtech.org/lesson6.7

Admittedly that's home bias, and I can't find this character in any official documentation on the topic. I also can't find it anywhere else in a very quick Google search.

As for your question about which is correct, since the question mark is above the equals sign, it seems to me like the question mark would appear before the vertical juxtaposition sign, since it is clearly the upper symbol.

**Comment by NSoiffer** [comment]
My bad -- I even quoted what ordering is suppose to happen and switched. So I agree with the order you have.

FYI: The APH lessons are official enough for me...

Hard coding the G1 word indicators isn't correct because the character could occur in a G1 passage mode, so if they were there, it would be incorrect.

My code currently won't coalesce the G1 indicators in the symbol to get the word mode for it and the encoding in the APH lessons is better than using G1 passage mode. Interestingly, I apparently at one point allowed for a G1 word mode indicator but took it out because I never used it. Now I have a use for it...
