### ISSUE TITLE
Nemeth: Right space missing after question mark over equals operator in long-form MathML

### ISSUE THREAD

**Issue by rob-aph** [NSoiffer/MathCAT#152]
[updated to include MathML in block quotes]

I translated the following in Nemeth mode:
```
<math >
    <mn>7</mn>
    <mover>
        <mo>=</mo>
        <mo>?</mo>
    </mover>
    <mn>8</mn>
</math>
```
I got the following result:
⠼⠶⠀⠐⠨⠅⠣⠸⠦⠻⠼⠦

I'm not sure if this is proper MathML or not, but a space is missing before the 8 in the result. If I write the MathML to use the Unicode character Questioned Equal To in <mo> tags instead, the space is included.

**Comment by NSoiffer** [comment]
@rob-aph: FYI, when you include MathML, it should be in block quotes (a line with three back quotes, the mathml, a line with three back quotes). Otherwise the display is messed up.

The bug happens because there is a Nemeth rule to remove space after a punctuation. MathCAT's cleanup rules don't really know about punctuation symbols other than they are one or two characters long and begin with a "P" (to mark they are punctuation). In this case, the terminator indicator for being modified (⠻) gets interpreted as being part of the punctuation symbol so the cleanup fires. I need to exclude the terminator from a legal match.

I want to added a test for this. Preferably one that comes from the Nemeth book or some other "trusted" source. Do you have one that I can reference in the test?

**Comment by rob-aph** [comment]
Unfortunately, I don't have an official source/test case for this. I fell over it accidentally while working on the UEB issue for questioned equal to, just to see if/how you were handling it in Nemeth, and realized that the output could be changed by changing the MathML, but expressing the same thing.

**Comment by NSoiffer** [comment]
Ok. I've added a test with some comments referencing this bug.
