### ISSUE TITLE
UEB: Too many grade 1 indicators

### ISSUE THREAD

**Issue by rob-aph** [NSoiffer/MathCAT#170]
With the following input:
```
<math>
	<mo>∫</mo>
	<mn>3</mn>
	<msup>
		<mi>x</mi>
			<mn>2</mn>
	</msup>
	<mi>dx</mi>
</math>
```

I get the following Braille output:
⠰⠰⠮⠼⠉⠭⠔⠼⠃⠰⠙⠭

The initial grade 1 indicator is unnecessary, as one, for next symbol, is enough. This seems to be related to the fact that a grade 1 indicator is required before DX, as changing the input to an equation which does not require this fixes the problem.

**Comment by NSoiffer** [comment]
Using the (hopefully not too confusing) notation in MathCAT, this is what MathCAT has going into the cleanup phase:
```
1⠮N⠉L⠭1⠔N⠃#L⠙L⠭``
```
The '1' signals a G1 indicator and the '#' signals the end of the script.

I'm probably forgetting something because my code internally thinks that starting with just symbol mode gives `1⠮N⠉L⠭⠔N⠃1L⠙L⠭` (no '1' before superscript indicator, but '1' before the 'd' because it follows a number), but it seems that if it starts in symbol mode, then we need a G1 indicator before the superscript. What am I missing?

**Comment by rob-aph** [comment]
So far, I'm really lost, not quite able to get my head into your world. I assume by mode you mean symbol, word, or passage. I see the enum for these and do understand that much. I don't what mode we are in at the start of the equation.

I also don't understand that '#' signals the end of the script. What script? Is it a specific rule? If so, which one? And, why is the end where it is, and not at the end of the equation?
 
Still trying...

**Comment by NSoiffer** [comment]
In UEB, there is typically Symbol, Word, and Passage mode for several things. For example, capitalization and grade 1.

For UEB (and other braille codes), MathCAT takes a post pass to figure out which mode to use for capitalization (combining sequences of caps). It also takes a pass to remove unneeded mode changes. Finally, it calculates what the string looks like if it starts in G2 mode, if it starts by adding G1 word mode indicators, and finally if it starts by adding G1 passage indicators.

For all of this to work, the extended braille string that MathCAT generates adds "L" for letters, "N" for numbers, '1' for required G1 mode, and many more letters for other cases. This allows the post pass to easily recognize letters, etc., and do the right thing (e.g., a-j following a number forces G1 mode).

If you have a digit following a number in a script (e.g., $x^2$ or $x_1$), then you need to flag that script has ended so that you add a numeric indicator in front of what follows the script. That is what '#' is used for.

Back to the example you flagged: the superscript indicator `⠔` has to be in G1, as does the symbol for integral. Doesn't that mean using G1 word mode makes sense because that way you don't have two G1 symbol indicators? BANA guidance (which some of their examples don't follow) says to use a G1 word indicator if a G1 indicator is required after the third cell.

**Comment by rob-aph** [comment]
The problem is that the superscript indicator is already in G1 because of the numeric indicator. I think that's what you are missing (to answer your question from your first comment.) So, the code is correct to strip the '1' before the superscript indicator.

**Comment by NSoiffer** [comment]
Thanks. I forgot about that -- I've recently implemented two non-English braille codes and it is mudding my memory.

I think the problem is that `is_grade2_string_ok()` is messing up. It could be that `is_forced_grade1()` is buggy, which it calls. I'll try to figure it out on Thursday if I remember.

**Comment by NSoiffer** [comment]
Off by one bug.
