### ISSUE TITLE
Report Math blocks as "math" and not "clickable"

### ISSUE THREAD

**Issue by bhavyashah** [NSoiffer/MathCAT#190]
"Clickable" is three syllables and it gets a bit inefficient to hear it preceding a Math block each time. "Math" is one syllable so snappier. It also helps a Math block stand out from generic clickable elements on a webpage. While the former is technically a subset of the latter, it really isn't clickable in the traditional sense either - there just happens to be granular navigation for a Math block that can be accessed by clicking into it.

**Comment by NSoiffer** [comment]
I agree with your suggestions, but this doesn't come from MathCAT, it is coming from NVDA. In fact, it is likely coming from the web page itself. In particular, I remember seeing this on pages that use MathJax, so I think it is some setting/attribute that MathJax creates. If you verify that MathJaX is doing the display (simulate a right click on an equation and see if a MathJax menu comes up), I think you should [file a bug with them](https://github.com/mathjax/MathJax-src/issues).

Closing because there's nothing I can do.

**Comment by andrew-l-d** [comment]
Neil is correct, "clickable" comes from the website.  This edit field, for example, is presented as clickable.  I do not have the patience to dig into the source code to find out why.  Forms I write do not have edit fields announced as clickable.  I invariably turn off the clickable announcement in NVDA because it almost always just adds clutter.
Andrew
