### ISSUE TITLE
UEB: Grade 1 indicators missing for variables in parentheses

### ISSUE THREAD

**Issue by rob-aph** [NSoiffer/MathCAT#205]
Consider the following:
```
<math> <mo>(</mo> <mi>x</mi> <mo>,</mo> <mi>y</mi> <mo>,</mo> <mi>z</mi> <mo>)</mo> </math>
```

Computed braille string:
⠐⠣⠭⠂⠀⠽⠂⠀⠰⠵⠐⠜
Should be:
⠐⠣⠰⠭⠂⠀⠰⠽⠂⠀⠰⠵⠐⠜

For some reason, the last variable is always correctly marked with the grade 1 indicator.

**Comment by NSoiffer** [comment]
This seems to be related to the standing alone rule, something I struggled to understand. In RUEB 2.6.3, it mentions "comma, semicolon, colon, full stop (period), ellipsis, exclamation mark or question mark". Others chars such as parens and quotes are listed, but those are all covered.

In the Unicode files, you can indicate whether something is part of a standing alone rule with 'o', 'c', or 'b' (open, close, or both). Comma, colon, and dot are missing that indication.  For ";" and "?", they also get a G1 marker. Does the G1 marker for ";" and "?" make sense? Should others get a G1 marker?

When I add "c" for ",", I get the output `⠰⠰⠰⠐⠣⠭⠂⠀⠽⠂⠀⠵⠐⠜⠰⠄` which kind of avoids the issue. I can see it wants to use G1 mode if it had used symbol mode. Forcing G1 passage mode happens because of the 3 G1 indicators that would have been needed in other modes. Does this seem reasonable?

With this change, one test fails (example_11_5_6) because it switches to G1 passage mode. I'm not sure why that happens, but the output then because consistent with the output listed in GTM but is not consistent with the following from BANA (from the code):
```
        // From http://www.brailleauthority.org/ueb/ueb_math_guidance/final_for_posting_ueb_math_guidance_may_2019_102419.pdf
        //   Unless a math expression can be correctly represented with only a grade 1 symbol indicator in the first three cells
        //   or before a single letter standing alone anywhere in the expression,
        //   begin the expression with a grade 1 word indicator (or a passage indicator if the expression includes spaces)
        // Apparently "only a grade 1 symbol..." means at most one grade 1 symbol based on some examples (GTM 6.4, example 4)
```
Section 1.7 in GTM (e.g., 1.7.3)

**Comment by NSoiffer** [comment]
I'm going to close this (and change the test) and accept the form listed in example 11.5(6) (G1 passage mode). There needs to be a G1 before the x and the y in the example. That two needs and the BANA rule sort of says "1", although I never got clear guidance on what the "rule" really is.

If you disagree, please reopen and give some guidance on when word and passage should be used.
