### ISSUE TITLE
Improve reading of limits

### ISSUE THREAD

**Issue by bhavyashah** [NSoiffer/MathCAT#207]
Consider the following:
```
<math xmlns='http://www.w3.org/1998/Math/MathML'>
 <munder>
  <mrow>
    <mi>lim</mi>
    <mo>&#x2061;</mo>
  </mrow>
  <mrow>
    <mi>n</mi>
    <mo>→</mo>
    <mi mathvariant='normal'>∞</mi>
  </mrow>
 </munder>
</math>
```
The limit is read as "     modified lim  of with      n      right arrow  infinity below."
I am not sure how it is spoken in other circles, I have always spoken it as "limit n tends to infinity" (or perhaps " approaches instead of tends, and tending instead of tends). The current reading is a bit confusing and verbose.

**Comment by NSoiffer** [comment]
Where did this MathML come from? The `<mo>&#x2061;</mo>` that is part of the `mrow` with `lim` is wrong.  `&#x2061;` is "invisible function apply" and that only makes sense _after_ `munder`, not as part of it. If it isn't there, then it reads as "the limit as n approaches infinity".

If  `<mo>&#x2061;</mo>` is coming from a common tool, I'll try and introduce a clean up.

**Comment by bhavyashah** [comment]
This came from ChatGPT > GPT4 > Default. One prompt you can use is "State three common limits where n tends to infinity." I did have a strong feeling that I've seen this elsewhere too. I quickly looked online and here's a Wikipedia page that has contents that read similarly: https://en.wikipedia.org/wiki/List_of_limits. Read what comes after "The limit superior and limit inferior of a sequence are defined as."

**Comment by NSoiffer** [comment]
I used GPT4 from openai.com and didn't get that result.

The wikipedia pages sound poor because they aren't 'lim' -- MathCAT didn't have rules for "lim inf" and "lim sup". Even I had added them, I never would have guess that the space between "lim" and "inf" is U+2006. I just added rule that will handle that.

Fixed in [87772db](https://github.com/NSoiffer/MathCAT/commit/87772db83dc5732d3751657ced8e849b9a4cc6f8).

**Comment by bhavyashah** [comment]
Confirming that some cases have been fixed in the new version - thanks!
Sorry that GPT4 didn't generate sufficiently similar results for us. Can you maybe try to toy with it a bit more by tweaking the prompt or such to see if it gives you limits read in the manner I described? I get the modified lims quite consistently on ChatGPT so am hoping that it will show up in your esting soon enough.
Let's work with Wikipedia pages for now.  Please read what comes after "Formally speaking, an estimator Tn of parameter θ is said to be weakly consistent, if it converges in probability to the true value of the parameter:[1]" on https://en.wikipedia.org/wiki/Consistent_estimator for another potential case.

**Comment by bhavyashah** [comment]
Also, for GPT4 testing, please use Microsoft Edge. Not sure why but on Firefox, the limits are rendered differently as "     lim  of sub      n      right arrow  infinity."

**Comment by NSoiffer** [comment]
I've never seen "plim" as a variant of "limit" before. I can add a rule for it. What would you like it to say? Maybe "p lim" for a terse reading and "probabilistic limit" otherwise?

Also, "Pr" is used for "probability" on that page. Do yo want that read as "Probability"? Reading "P" as probability is a bit dangerous without more context, but I think it is safe for "Pr".

**Comment by bhavyashah** [comment]
What do you mean by a "first reading" and "otherwise?" Can you give another example of where MathCAT reads something differently the first time VS every time after?
I am honestly conflicted between expanding to "probability" for plim or pr. It would probably clarify things and improve comprehension, but it also feels like verbosity that could add up if I am going through a document filled with expressions containing plenty of pro-ba-bi-li-ty's. I am not sure.
Also, I mainly wanted to draw your attention to the "with      n      right arrow  infinity below" part within "   plim with      n      right arrow  infinity below                   t     sub      n     is equal to  theta."

**Comment by NSoiffer** [comment]
> What do you mean by a "first reading" and "otherwise?" Can you give another example of where MathCAT reads something differently the first time VS every time after?

I didn't write that. I did mention a terse vs non-terse reading. The MathCAT settings allow you to control the verbosity of what is spoken.

> Also, I mainly wanted to draw your attention to the "with n right arrow infinity below" part within " plim with n right arrow infinity below t sub n is equal to theta."

I think that reading is a good reading when something is below something else. However, for certain notations, we have specialized ways of speaking those notations. The limit notation is one, sum and integrals are another ("sum _from_ i equals 0 to n"). But in order to speak the specialized method of speech, MathCAT needs to recognize the notation. If the base were "log", I don't think you'd want to hear "log as n goes to infinity".  So just because there is `n -> ∞` , you don't necessarily want to say "as n goes to infinity". I need to identify as many limit-like bases as possible. If you have a list, please let me know. Otherwise, I'll just have to add them one-by-one as you or others come across them.

**Comment by bhavyashah** [comment]
My bad for misreading (and misquoting) "terse" as "first." Unfortunately, I don't have a list but am happy to continue reporting atypical limit cases as I come across them. Expanding "pr" and "plim" to "probability" and "probability limit" for Verbose makes complete sense. Reading "plim" as "p lim" for Terse also makes sense to me. The reading for Medium (the mode I use) is debatable, but my preference I think is to expand it to "probability" and "probability limit."

**Comment by NSoiffer** [comment]
Thanks for confirming.

FYI: I've been working on two talks for a conference this week. That along with the conference means some bug fixes will be slow to happen, even if they are simple like this one.

**Comment by bhavyashah** [comment]
Of course, and good luck with the conference! :)
