### ISSUE TITLE
UEB: Double line bond

### ISSUE THREAD

**Issue by rob-aph** [NSoiffer/MathCAT#215]
I'm working on a possible pull request of dash and dash-like characters to add to UEB. I feel we need something for double line bond, which uses the dot pattern ⠨⠠⠤. Do you have a preference?

The following page may help:
```
https://en.wiktionary.org/wiki/Appendix:Variations_of_%22%3D%22,
```

**Comment by NSoiffer** [comment]
Definitely the equals sign. You probably saw this in the Nemeth file, but if you didn't, you should probably emulate this:
```
 - "=":                        # 0x003D (Equals sign)
    - test:
        if: "@data-chemical-bond"
        then: [t: "⠸⠶⠻"]
        else: [t: "⠨⠅"]
```

You can do the same for other bonds (search for `@data-chemical-bond` to see other uses. Sometimes, `::` is used for a double bond. That's two characters, so it can't go into `unicode.yaml`. Look in `en/SharedRules/general.yaml` and you'll see an alternative way to handle it that works for more notations.

**Comment by NSoiffer** [comment]
Also, add tests if you can.

MathCAT needs enough context to recognize chemistry so that it adds the `data-chemical-bond` attribute. An example is:
```
#[test]
fn ethylene_with_bond() {
  let expr = "<math><mrow>
          <msub><mi>H</mi><mn>2</mn></msub><mi>C</mi>
          <mo>=</mo>
          <mi>C</mi><msub><mi>H</mi><mn>2</mn></msub>
      </mrow></math>";
  test_prefs("en", "SimpleSpeak", vec![("Verbosity", "Terse")], expr, "cap h, 2 cap c, double bond cap c, cap h, 2");
}
```
You can repurpose that test.

One of these days, I'll switch it over to use the (proposed) MathML `:chemical-formula` `intent` property. Then you should be able to mark up any MathML with `intent=`:chemical-formula` (e.g., on an `mrow` or `math` element) and it will assume the children are a chemical formula, not an equation.

**Comment by rob-aph** [comment]
I'm afraid I'm in over my head on this one.
