### ISSUE TITLE
Can not navigate through `$H_2SO_4$` in MathCAT Demo site

### ISSUE THREAD

**Issue by hjy1210** [NSoiffer/MathCAT#218]
In [MathCAT Demo](https://nsoiffer.github.io/MathCATDemo/), type `$H_2SO_4$` in Math Input Area, press `Generate Speech and Braille`,
click into Display Math rectangle, we CANNOT navigate through formula and the web page can not response any more.

But if replace `$H_2SO_4$` with `$h_2so_4$`,  we can navigate through.

**Comment by NSoiffer** [comment]
Thanks. I found the problem in the navigation that caused the crash, but the real problem is a bug in the code corrects the output to be correct for Chemistry -- it is generating some garbage MathML and that caused the navigation code to crash because an assumption it had wasn't true for the bad code.
