### ISSUE TITLE
UEB: Omission character emitted for empty MathML tags

### ISSUE THREAD

**Issue by rob-aph** [NSoiffer/MathCAT#227]
If I send the following to MathCAT:
```
<math> </math>
```
I get ⠬ as the computed braille string. This seems od, but while on the topic, I'm wondering what one sends to MathCAT to intentionally get this result?

**Comment by NSoiffer** [comment]
I've been working on the space/omission code for the last several days. There is no obvious method to tell if a space is an omission or just a space, but my changes are at least moving towards making it clearer in what MathCAT does. One of the changes is to attempt to measure the size of a space and if it is big enough (still deciding on the cutoff, but probably 1em to 1.3em), it is an omission otherwise just a space. A single non-breaking space in the new code will be a space but two of them will be an omission. The idea being that an omission should be more obvious. 

If the space is small (maybe < 0.25em), then it is thrown out as a spacing tweak and not a true intended space.

The best solution is for the author to state what they mean. The MathML WG has tentatively added `intent='blank'` as a way of marking an omission. Some example usages are:
```
<mi intent='blank'>__</mi>
<mi intent='blank'>?</mi>
<mo intent='blank'>□</mo>
<mspace intent='blank' width='3em'/>
<menclose intent='blank' notation='box'> <mspace width='3em'/> </menclose>
```

We probably should also add either a 'this space intentionally added' or 'this space is just a tweak' concept also.

To answer your question, you can write:
```
<math>
   <mspace intent='blank' width='2em'/>
</math>
```

There are lots of other methods that should work after I finish my rewrite, but using `mspace` gives you control over how wide the space should be.

**Comment by NSoiffer** [comment]
I've checked in code that does what I mentioned above. Additionally, if the space is wide enough (two non-breaking spaces or an mspace with `width='1.3em'` or greater, that will be consider an omission also. Specifying `intent=':blank' is safest.
