### ISSUE TITLE
UEB: Trouble with xor symbol

### ISSUE THREAD

**Issue by rob-aph** [NSoiffer/MathCAT#245]
As far as I can tell, the following should use grade 1 word mode:
```
<math> <mi>p</mi> <mo>&#x22bb;</mo> <mi>q</mi> </math>
```
output:
⠏⠈⠖⠠⠱⠟
should be:
⠰⠰⠏⠈⠖⠠⠱⠟

This is a hard one to solve, because it appears that the only part of the equation which could be interpreted as grade 2 content is ⠠⠱, the bar under previous symbol, which could be misinterpreted as Wh. The complexity is that the xor symbol, ⠈⠖⠠⠱, is actually two braille symbols which are treated as one -- xor and bar under previous. Because of this, marking this symbol as a grade 1 symbol would be incorrect. (The xor symbol, ⠈⠖, does not require grade 1 mode.)

This example comes from the APH UEB MathTutorial, lesson 10.3, example 11:
```
https://uebmath.aphtech.org/lesson10.3
```

I consulted with a transcriber on this issue, who feels the tutorial is correct.

**Comment by NSoiffer** [comment]
Wow. That's a mess! Would a correct solution say that character has to be in G1 word or passage mode?

There is one other character that I see that uses this solution:
```
 - "≟": [t: "𝟙⠦⠻⠐⠶"]           # 0x225F (Questioned equal to)
```
That is used in example 5 in the [APH lesson 6.7](https://uebmath.aphtech.org/lesson6.7). In that case, the G1 word indicator in front of the symbol works because it is a comparison symbol and so is spaced. 

For the xor symbol, doing that I get `⠏⠰⠰⠈⠖⠠⠱⠟`. I think this is technically correct, but not great. I can probably fix that by moving the G1 word indicator backwards to the start of the word it is part of. I'm not sure how hard that is though.

Do you know of any other symbols that similar problems? There are lots of composite characters that set G1 symbol mode, but which other ones should set a G1 word mode?

**Comment by NSoiffer** [comment]
I managed to get the code to pull the Word indicator forward so it now produces `⠰⠰⠏⠈⠖⠠⠱⠟`. I've added a test for this.

@rob-aph: please let me know if there are other symbols that need this fix.
