### ISSUE TITLE
MathML fails to translate

### ISSUE THREAD

**Issue by mwhapples** [NSoiffer/MathCAT#295]
I have encountered the following MathML failing to translate with MathCAT. I first found this with BrailleBlaster but it also shows with the online demo. The MathML is:
```
<math altimg="images/U01C02/p097-004.png" id="image767" display="inline" alttext=""><mi>P</mi><mo>⁢</mo><mi>Q</mi><mo>+</mo><mi>Q</mi><mo>⁢</mo><mi>R</mi><mo>=</mo><mi>R</mi><mo>⁢</mo><mi>S</mi><mo>+</mo><mi>Q</mi><mo>⁢</mo><mi>R</mi></math>
```
I suspected that the math element having multiple child elements was the cause so I tried wrapping them in a mrow so that the mrow was the only direct child of the math element. No success with that modification. This example came from a NIMAS book so is some MathML out there.

**Comment by NSoiffer** [comment]
I was able to replicate a crash for UEB. Speech and Nemeth work correctly, so it is UEB bug. That appears to be related to trying to do something with the  Capital symbol/word/passage mode:
```
assertion failed: cap_mode == UEB_Duration::Symbol
```
Do you know if it should be using capital passage mode, or if it should be sticking to symbol mode? It's been a while since I read the UEB spec.

**Comment by NSoiffer** [comment]
Changing the assert results in MathCAT wanting to use several word capitalization's:
   ⠠⠠⠏⠟⠐⠖⠠⠠⠟⠗⠀⠐⠶⠀⠠⠠⠗⠎⠐⠖⠠⠠⠟⠗
Should it use passage mode?

**Comment by mwhapples** [comment]
I am not sure whether it should use passage mode, I would need to look it up. I have a feeling this may be one of those more complex parts of the rules.

**Comment by NSoiffer** [comment]
In the technical guide, I only see there two mentions:

> 1.6 Capitalisation
> In mathematics and science, strings of capital letters often occur, for example in
> a geometrical name, in a physics formula or in genetics. Such strings should
> always be uncontracted. Capital word indicators (double caps) are normally
> used. See Section 16 for advice on capital letters in chemical formulae. It is
> preferable to also use this approach in genetics or other topics where there are
> frequent changes of case within a sequence of letters.

> 16.2 Chemical formulae
> Use of capital indicators and terminators: The general UEB principles on the
> choice of single letter, word or passage mode apply; in particular, a capital
> terminator should not be used within a two-letter chemical element symbol. Using
> single capital indicators for chemical formulae provides a uniform appearance to
> the braille; nevertheless, there may be a clear advantage in using capital
> passage mode in some cases. Letters representing chemical elements should
> never be contracted.

In the main spec, there is:

> 8.8 Choice of capitalised indicators
> Note: While the default treatment for a sequence of capital letters is
> capitals word mode, there are situations where the transcriber has a
> choice between using either individual capital letters or capitals word
> mode. If both choices will render an unambiguous transcription,
> interpret the following rules as guidelines.
> 8.8.1 Choose the method which retains the usual braille form.
> 8.8.2 Choose the method which best conveys the meaning. In particular,
> choose a method that avoids the need for capital indicators or
> terminators within natural subunits of an expression. 
> 8.8.3 Choose the method which gives consistency throughout a single title.

_Maybe_ a passage indicator is better because it retains the usual braille form. On the other hand, the cap word indicator reinforces/reminds that the next two letters are capitals.  In terms of character count, using word indicators is 6 extra chars and using a passage indicator (which requires an end passage indicator) is five characters. So there isn't a big difference (in this example).

I'll commit the crash fix that results in word capitalization mode, but if you or someone else (@rob-aph?) can say it should be passage mode (and why), I'll change this.

**Comment by NSoiffer** [comment]
I heard back from someone who knows UEB. She said she couldn't find any rule that said which to use, but her sense is that the less (cap) indicators, the better since it lets the reader focus on the content. So now the output is `⠠⠠⠠⠏⠟⠐⠖⠟⠗⠀⠐⠶⠀⠗⠎⠐⠖⠟⠗⠠⠄`. It is three characters shorter than the Word mode output (I miscounted before).

In looking at the code more closely that decides on passage mode, I counted the capital indicators incorrectly. So it was a bug that it didn't use passage mode. The code will use passage mode whenever it is both legal and shorter.
