### ISSUE TITLE
Erroneous truncated output from MathML with <mmultiscripts>

### ISSUE THREAD

**Issue by brichwin** [NSoiffer/MathCAT#42]
Sample MathML from the MathML3 spec for <mmultiscripts> generated both truncated speech output and erroneous Nemeth braille output.

The MathML for:
![image](https://user-images.githubusercontent.com/117550/174187828-8f0d30ca-1375-458e-9682-d5ea5f994b53.png)

```xml
 <math>
  <mmultiscripts>
    <mi>R</mi>
    <mi>i</mi>
    <none></none>
    <none></none>
    <mi>j</mi>
    <mi>k</mi>
    <none></none>
    <mi>l</mi>
    <none></none>
  </mmultiscripts>
 </math>
```

Resulted in speech output of simply 'R' from the MathCAT demo and 'cap r' from MathCAT.

The Nemeth braille output received from MathCAT demo was (cap r subscript i):
```
⠠⠗⠰⠊
```

### Expected Output
The Duxbury braille translator produced the following braille for the above example:
```
⠠⠗⠰⠊⠅⠇⠘⠚
```

The MathJax SRE 4.0 produced the following MathSpeak Grammar verbose output which seems to mirror the Duxbury braille:
```
upper R Subscript i k l Superscript j
```

I am not sure if the order of the subscripts and superscripts is important? Neither Duxbury's braille nor MathJax SRE's speech honored the sequence as rendered.

**Comment by NSoiffer** [comment]
Seems like AT is batting 0% on this one. It's a tensor notation and the position of the indices matter. I'm not sure what the semantic speech should be, but it is probably something like
```
cap R with indices lower i, upper j, lower k, lower l
```

I'm going to need to some digging about what is appropriate in braille. Tensor notation is way above what UEB covers in their instructions/examples. I don't remember seeing it in the Nemeth book either. The problem is that the pairs matter (each pair is like matrix entry), and a singleton index is accessing the row/col (depending on whether it is a sub/superscript). Because of this, you can't say the `k` is a subscript of expression that precedes it -- it is sort of a continuation of the preceding scripts.

If you see something in Nemeth or UEB that seems like it might cover this, please me know.

**Comment by brichwin** [comment]
I'm not sure if the following adds anything, I tried creating a LaTeX equivalent:
```tex
R_i{}^j{}_k{}_l
```
In the MathCAT demo, the LaTeX snip created a similar visual rendering and provided the following text and braille:
- Clearspeak: `R sub i, with 3 prescripts, none j k none l none`
- Nemeth braille: `⠠⠗⠰⠊⠘⠚⠐`

In the [MathML 3 spec, section 3.4.7.1](https://www.w3.org/TR/MathML3/chapter3.html#id.3.4.7.1) it says:
> The argument sequence consists of the base followed by zero or more pairs of vertically-aligned subscripts and superscripts (in that order) that represent all of the postscripts. 

I'm out of my depth here! It seems MathCAT/Clearspeak recognized the multiscript nature and I'm guessing it is incorrect in using "prescripts" instead of "postscripts"; And, isn't the i part of the postscripts?. Assuming I understand that model, I would have expected `R with 4 postscripts, i none, none j, k none, l none` (adding commas to aid in perceiving postscript pairs).

I'm guessing the indication of "none" for missing scripts is useful - However, your suggested speech of "cap R with indices lower i, upper j, lower k, lower l" seems easier to listen to.

The braille output appears to be truncated again... it looks like it attempted to add a back to base indicator after the superscript k and then stopped for some reason. I'm a member of the National Braille Association, so I can post in their forums. I'll ask there if anyone knows how to handle multiscripts (assuming I can craft the question correctly).

**Comment by brichwin** [comment]
Mary Stores pointed out to me that Nemeth Rule XIII Section 82 describes both Simultaneous as well as Non-Simultaneous superscripts and subscripts (page 96) - The non-simultaneous examples appears to describe Nemeth braille for prescripts and postscripts similar to the tensor indices notation:
![image](https://user-images.githubusercontent.com/117550/175196165-b425d38d-2ad6-469e-ac0e-3d7f7e3ffb4a.png)

**Comment by NSoiffer** [comment]
I'm getting close to getting mmultiscripts right.

The Duxbury output is not correct: `⠠⠗⠰⠊⠅⠇⠘⠚` in ascii braille is `,r;ikl^j`. In that form, it is easy to see that the order of the indicies has been lost.  According to 82.b (above) a baseline indicator (dot 5) is needed between the scripts, and there are none in the Duxbury output, so that's another mistake.

**Comment by brichwin** [comment]
Certainly - Mary and I could run tests through Duxbury, if that's what you mean.

**Comment by NSoiffer** [comment]
I'm very curious to know how well MathCAT stacks up against Duxbury, so the more tests you are willing to run, the better.

Here's what MathCAT now produces (Nemeth and ASCII braille):
```
⠠⠗⠰⠊⠐⠘⠚⠐⠰⠅⠐⠰⠇
,r;i"^j";k";l
```
Does this look right?

I need to fix the UEB next.

**Comment by brichwin** [comment]
I received feedback on the post I made on the National Braille Association's Nemeth Code for Math and Science forum. My original post was eaten by their SPAM filter due to the links I put in it. Here is Lindy Walton's reply:
From: https://www.nationalbraille.org/forums/topic/missing-post-nemeth-for-tensor-indices-notation-multiscripts/#post-39442
![image](https://user-images.githubusercontent.com/117550/196965576-19f76070-afc4-4f34-947e-f5cff9ec83b2.png)

**Comment by brichwin** [comment]
Well, Duxbury doesn't do well with this:
![image](https://user-images.githubusercontent.com/117550/196991417-98cddfb2-9a0e-48ae-a89a-b0f271912c4b.png)
![image](https://user-images.githubusercontent.com/117550/196991478-fd63f83d-5851-4986-b752-d2aff3ff7ad2.png)

The ASCII and Unicode versions:
,r;ikl^j
⠠⠗⠰⠊⠅⠇⠘⠚

I might write this up and send it to Duxbury as an issue as well.

**Comment by NSoiffer** [comment]
@brichwin: could you check with Lindy about the translation. I don't think she realized that the `k` and the `l` are in separate subscripts. Lindy's Nemeth translation places them in the same subscript. That is mathematically wrong because it would imply the last tensor index is "k times l" whereas there are actually four of them and the 'k' and 'l' are not (implied) multiplication.  With that correction (and knowing that MathCAT leaves it up the to caller to add the Nemeth switch indicators), `⠠⠗⠰⠊⠐⠘⠚⠐⠰⠅⠐⠰⠇` as the correct MathCAT generates appears correct.

**Comment by NSoiffer** [comment]
@brichwin: thanks for checking.
