### ISSUE TITLE
Failing to parse MathML maybe due to empty cells

### ISSUE THREAD

**Issue by ajirving** [NSoiffer/MathCAT#88]
Trying to read https://en.wikipedia.org/wiki/Polynomial_decomposition
with NVDA I get various equations that can't be parsed.  Assuming the page doesn't get updated the first one is immediately after "Less trivially".  Incidentally the exception handling can't be working correctly because I can't arrow down the page any further than this point but that should probably be raised as an issue on the Python repo.  The error from the NVDA log is 
```
    libmathcat.SetMathML(mathml)
pyo3_runtime.PanicException: as_element: internal error -- found non-element child (text? 'Some(Text { text: "" })')
```

My suspicion is that the issue is caused by some of the cells in this multiline environment being empty.  I don't know whether this is valid MathML.

I've [attached](https://github.com/NSoiffer/MathCAT/files/10610833/mathml.txt) the rather llong MathML.

**Comment by NSoiffer** [comment]
Thanks for the bug report.

I'm not able to replicate this with the current beta build. I have attached the beta of the addon (unzip it to get `MathCAT-0.2.0.nvda-addon` and then use "manage addons" to install it); github doesn't support attaching that file type). Please give it a try and let me know if the problem still exists for you.

I hope to release this "any week now", but I've been saying that for two months. I'm working with some translators on simplifying translations.
[MathCAT-0.2.0.nvda-addon.zip](https://github.com/NSoiffer/MathCAT/files/10611507/MathCAT-0.2.0.nvda-addon.zip)

As for the crash happening and forcing a restart. It happens because the code has come across something very wrong -- it should never have gotten to that state and recovery is hard at that point. The real problem happened elsewhere (e.g., maybe because it doesn't handle empty cells [which it seems to do now]). It looks like there is a hook I can change when MathCAT panics. I'll open a separate issue for that.

**Comment by ajirving** [comment]
Thanks, unfortunately it still fails for me with the Beta.  I copied the MathML into a simple Rust test and reproduced it with a current git clone.  I therefore don't understand how it can be working for you, could you be getting different generated MathML?

**Comment by NSoiffer** [comment]
It worked for me on the Wikipedia page, but using your example, it crashes. 

I have traced it down to:
```
<mrow class='MJX-TeXAtom-ORD'>

 </mrow>
```
I have code and tests for an empty `mrow`, but this falls through the cracks because from a parsing perspective, it isn't empty, it has textual content.
