### ISSUE TITLE
Some MathML can cause panic

### ISSUE THREAD

**Issue by mwhapples** [NSoiffer/MathCAT#94]
I have encountered some MathML which can cause MathCAT to panic. An example of such MathML is: <m:math xmlns:dtbook="http://www.daisy.org/z3986/2005/dtbook/" display="inline" id="math-205" altimg="./images/CH01/p057-006.jpg" alttext="mathimage" overflow="scroll"><m:mrow><m:msqrt><m:mrow><m:mstyle mathvariant="bold" mathsize="normal"><m:mn>0</m:mn></m:mstyle><m:mstyle mathvariant="bold" mathsize="normal"><m:mo>.</m:mo><m:mn>0</m:mn><m:mn>2</m:mn></m:mstyle></m:mrow></m:msqrt></m:mrow></m:math>
The above MathML is from a book, so whilst I feel the MathML is not great, it is a real example of what is out there.

**Comment by NSoiffer** [comment]
## Bug
@mwhapples: thanks for sending that in. The crash is happening in the clean up phase. The code assumed `mn` always has a parent (e.g., `math`), but in fact at that point in the cleanup, the `mn` is detached from the tree because the `mstyle` parent is thrown out. I need to figure out whether is makes sense to reattach the `mn` or whether the parent context should be passed as a parameter.

## Cleanup Question

The MathML indeed is not good.  "0.02" is spread into three separate `mn`s. MathCAT brings together the ".02", but because the initial "0" is in a different `mstyle`, the cleanup isn't smart enough to find it and bring it into the same `mn`. It's doable, but kind of messy. Do you think MathCAT should try to do this repair?

## Not Really MathML...
As a free floating piece of MathML, this is not valid MathML. It uses the `m` namespace, but instead of defining it inside the `math` tag, the `dtbook` namespace is defined. So technically, this is not MathML.

Do you know what MathML generator produced this?

**Comment by mwhapples** [comment]
That specific MathML sample comes from importing a nimas book (NIMAS_9780079066176.xml) into a development build of BrailleBlaster. The m namespace is declared elsewhere in the document, we probably should do better in placing the namespace declaration on the MathML so the fragments we send to MathCAT is valid. I don't know what tools created the MathML, but I think APH can send feedback to the publisher.
In that development build of BrailleBlaster I can create similar MathML with ASCIIMath and this does contain the namespace declaration but I get the same problem: <math xmlns="http://www.w3.org/1998/Math/MathML" alttext="sqrt(bb 0 bb(. 0 2))"><msqrt><mrow><mstyle mathvariant="bold"><mn>0</mn></mstyle><mstyle mathvariant="bold"><mrow><mo>.</mo><mn>0</mn><mn>2</mn></mrow></mstyle></mrow></msqrt></math>
In this specific example may be clean up could merge the adjacent mstyle elements as they are the same style. This though does not generalise as this MathML will also cause the panic: <math xmlns="http://www.w3.org/1998/Math/MathML" alttext="0 bb(. 0 2)"><mn>0</mn><mstyle mathvariant="bold"><mrow><mo>.</mo><mn>0</mn><mn>2</mn></mrow></mstyle></math> and here no such merging could be done.

**Comment by mwhapples** [comment]
Also the error seems to rely upon the second mstyle starting with a <mo>.</mo> as the following MathML does not cause the issue: <math alttext="sqrt(bb 0 bb(0 2))" xmlns="http://www.w3.org/1998/Math/MathML" xmlns:utd="http://brailleblaster.org/ns/utd"><msqrt><mrow><mstyle mathvariant="bold"><mn>0</mn></mstyle><mstyle mathvariant="bold"><mrow><mn>0</mn><mn>2</mn></mrow></mstyle></mrow></msqrt></math>

**Comment by NSoiffer** [comment]
@mwhapples: Let me know if run into other problems -- this one is fixed.

**Comment by NSoiffer** [comment]
@mwhapples: I'm internationalizing the number cleanup code (#91) and temporarily broke this as I'm rewriting the code. I want to understand/try out what it does and document which system produces an `<mn>` for every digit
```
...<m:mn>0</m:mn><m:mn>2</m:mn>...
```
Do you know what software produced that example?

**Comment by mwhapples** [comment]
I am not sure what software was used, but I know that the file was a nimas book from the nimac. Would you like me to get more information? I could try and find our internal issue at APH relating to this and so find the nimas file causing it. I possibly could then try and find out how that specific book was created, although this last part I don't know whether I would find an answer.

**Comment by NSoiffer** [comment]
If it is a lot of work, don't bother. However, it is useful to be able to mark tests with a source when there is unusual MathML as is the case for this test (I created a test based on the bug report). If the source ends up going belly up, then potentially code could be simplified in the future.

**Comment by mwhapples** [comment]
This is the nimas file causing the issue NIMAS_9780079066176.xml whether the XML was extracted from the zip by someone in APH or whether that is how it is in the nimac I am not sure. I will make enquiries to see whether we can find out who prepared this nimas file and with what software.

**Comment by mwhapples** [comment]
The answer I have regarding the software used to create the math content in this example was MathType. I don't know what they did to get each digit in a separate mn.

**Comment by NSoiffer** [comment]
MathType doesn't do that... at least any version of MathType that I know about. I appreciate you taking the time to get the answer.

I might remove this cleanup because it worries me. I have a couple of tests that fail because of it, but looking at the tests, I think I hand wrote them and they aren't realistic of what a MathML generator would do. So maybe I should change the tests.  Hmm...

**Comment by mwhapples** [comment]
I agree the MathML seems strange and I probably wouldn't expect MathType to create something like that. I don't know whether they were using MathType in a strange way or if something else was really involved. Regardless of how it was produced, as I said it does come from an actual NIMAS book, for BrailleBlaster supporting NIMAS books is important. So we need this MathML not to cause exceptions or panics, but may be BrailleBlaster should do some clean up of its own as well.

**Comment by NSoiffer** [comment]
The exception/panic is definitely gone. The question is whether to do the repair and try and recreate a number. It makes a difference in Nemeth because `,` and `.` are different inside a number in Nemeth.

**Comment by mwhapples** [comment]
If I were deciding this one, I think I would go with asking the question, is there any case where someone would intend to have each digit in its own mn and the reader is meant to know that. If the answer is yes then we should probably respect what the author created and where it has been used wrongly we should seek to get the document corrected. If no then treating it as a single number should be OK as its probably poor use of mark up. The yes answer is probably easier to determine for definite.

**Comment by NSoiffer** [comment]
The test case that fails is $b_{12}$
```
<math><msub><mi>b</mi><mrow><mn>1</mn><mn>2</mn></mrow></msub></math>
```
This markup, or one that adds an invisible separator between the 1 and the 2 is how it should be marked up. In reality, I think every MathML generator would produce `<mn>12</mn>`. I believe I created the test by hand.

So the answer is complicated: yes there is a case where it should be respected, but no, I don't think that case will come up in practice with some very rare exceptions involving hand editing.

**Comment by NSoiffer** [comment]
If I give MathJaX the input `x_{1 3} +z_{13}`, I get the following output:
```
<math xmlns="http://www.w3.org/1998/Math/MathML" display="block">
  <msub>
    <mi>x</mi>
    <mrow data-mjx-texclass="ORD">
      <mn>1</mn>
      <mn>3</mn>
    </mrow>
  </msub>
  <mo>+</mo>
  <msub>
    <mi>z</mi>
    <mn>13</mn>
  </msub>
</math>
```
Notice that if I space the `1` and `3`, it generates two `mn`s, so I was wrong about this not coming up in practice.

I think coalescing the `mn`s together is a bad idea. MathCAT won't panic, it may not produce the speech or braille you want if the numbers are broken up into their digits.

**Comment by NSoiffer** [comment]
Sorry to drag this out, but I had another idea as I was looking at the test case...

For the example I above ("x_{1 3}"), it makes sense to add the space in the sense that the subscript is not the number "13" but "1,3" with an invisible comma. But that doesn't make sense beyond a certain point. Maybe that is two digits or maybe it is 3. Your original case (if put back together) is "0.02". That's more than 2 digits. It also has a decimal separator, so that's another sign that maybe it should be put back together.

So maybe it makes sense to make the cake and eat it too...
